---
- name: "Major"
  color: "FF0000"
  description: "Major changes that break backwards compatibility."
- name: "Minor"
  color: "FFA500"
  description: "Minor changes that do not break backwards compatibility."
- name: "Patch"
  color: "008000"
  description: "Patches that fix bugs."
- name: "Prerelease"
  color: "0000FF"
  description: "Prerelease versions."