---
- name: "Major"
  color: "B60205"
  description: "Major changes that impact existing compatibility"
- name: "Minor"
  color: "D93F0B"
  description: "New features without breaking changes"
- name: "Patch"
  color: "0E8A16"
  description: "Bug fixes and minor improvements"
- name: "Prerelease"
  color: "1D76DB"
  description: "Test version for validation before release"
- name: "NoRelease"
  color: "000000"
  description: "Do not include in the release notes"
- name: "Bug"
  color: "d73a4a"
  description: "Something isn't working as expected"
- name: "Feature"
  color: "0052cc"
  description: "New feature request or suggestion"
- name: "Triage"
  color: "fbca04"
  description: "Issue needs to be examined by maintainers"