---
- name: "Major"
  color: "B60205"
  description: "Major changes that impact existing compatibility"
- name: "Minor"
  color: "D93F0B"
  description: "New features without breaking changes"
- name: "Patch"
  color: "0E8A16"
  description: "Bug fixes and minor improvements"
- name: "Prerelease"
  color: "1D76DB"
  description: "Test version for validation before release"