---
labels:
  # 🔥 Versioning & Releases
  - name: "Major"
    color: "B60205"
    description: "Major changes that impact existing compatibility"
  - name: "Minor"
    color: "D93F0B"
    description: "New features without breaking changes"
  - name: "Patch"
    color: "0E8A16"
    description: "Bug fixes and minor improvements"
  - name: "Prerelease"
    color: "1D76DB"
    description: "Test version for validation before release"
  - name: "NoRelease"
    color: "000000"
    description: "Do not include in the release notes"

  # 🐞 Bugs & Fixes
  - name: "Bug"
    color: "d73a4a"
    description: "Something isn't working as expected"
  - name: "Regression"
    color: "E99695"
    description: "Functionality that previously worked is broken"
  - name: "Security"
    color: "B60205"
    description: "Security-related fixes"

  # 🚀 Features & Enhancements
  - name: "Feature"
    color: "0052cc"
    description: "New feature request or suggestion"
  - name: "Enhancement"
    color: "0E8A16"
    description: "Improvement to an existing feature"
  - name: "Performance"
    color: "FBCA04"
    description: "Optimization and performance improvements"

  # 🎯 Workflow & Project Management
  - name: "Triage"
    color: "fbca04"
    description: "Issue needs to be examined by maintainers"
  - name: "Help Wanted"
    color: "008672"
    description: "Needs community contribution"
  - name: "Good First Issue"
    color: "7057FF"
    description: "Beginner-friendly issue"
  - name: "Documentation"
    color: "5319E7"
    description: "Related to docs, README, or wiki"