# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - NoRelease
  categories:
    - title: 🚨 Major Changes
      labels:
        - Major
    - title: ✨ New Features
      labels:
        - Minor
        - Feature
    - title: 🔧 Fixes & Improvements
      labels:
        - Patch
        - Bug
    - title: Other Changes
      labels:
        - '*'
