name: ➕ Add to project

run-name: "➕ Add to project - ${{ github.event.issue.title || github.event.pull_request.title }} (#${{ github.event.number }}) by @${{ github.actor }}"

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: ➕ Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/mchave3/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}