name: Process-PSModule

on:
  pull_request:
    branches:
      - main
      - beta
    types:
      - closed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  statuses: write
  pages: write
  id-token: write

jobs:
  Process-PSModule:
    if: github.event.pull_request.merged == true
    uses: PSModule/Process-PSModule/.github/workflows/workflow.yml@main
    secrets:
      APIKey: ${{ secrets.APIKEY }}
    with:
      SkipTests: All
      PublishDocs: false