name: 🔍 Test-SourceCode

run-name: "🔍 Test-SourceCode"

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  TestSourceCode-pwsh-ubuntu-latest:
    name: Test source code (pwsh, ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Test source code
        id: test
        uses: PSModule/Test-PSModule@main
        with:
          Path: src
          TestType: SourceCode

  TestSourceCode-pwsh-macos-latest:
    name: Test source code (pwsh, macos-latest)
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Test source code
        id: test
        uses: PSModule/Test-PSModule@main
        with:
          Path: src
          TestType: SourceCode

  TestSourceCode-pwsh-windows-latest:
    name: Test source code (pwsh, windows-latest)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Test source code
        id: test
        uses: PSModule/Test-PSModule@main
        with:
          Path: src
          TestType: SourceCode